# Aqui trabajamos con https://www.kaggle.com/datasets/prakharrathi25/copd-student-dataset

In [1]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import matplotlib as plt

import seaborn as sns

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("prakharrathi25/copd-student-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/prakharrathi25/copd-student-dataset/2.archive...

100%|██████████| 3.06k/3.06k [00:00<00:00, 6.56MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/prakharrathi25/copd-student-dataset/versions/2

In [3]:
import os

# List files in the downloaded path
file_list = os.listdir(path)
print("Files in dataset directory:", file_list)

Files in dataset directory: ['dataset.csv']

Now that we know the filename, let's load the CSV into a pandas DataFrame and display the first 5 rows.

In [4]:
# The correct CSV file name from the file_list output is 'dataset.csv'
csv_file_name = 'dataset.csv'
full_csv_path = os.path.join(path, csv_file_name)

df = pd.read_csv(full_csv_path)
display(df.head())

,Unnamed: 0,ID,AGE,PackHistory,COPDSEVERITY,MWT1,MWT2,MWT1Best,FEV1,FEV1PRED,...,SGRQ,AGEquartiles,copd,gender,smoking,Diabetes,muscular,hypertension,AtrialFib,IHD
0,1,58,77,60.0,SEVERE,120.0,120.0,120.0,1.21,36.0,...,69.55,4,3,1,2,1,0,0,1,0
1,2,57,79,50.0,MODERATE,165.0,176.0,176.0,1.09,56.0,...,44.24,4,2,0,2,1,0,0,1,1
2,3,62,80,11.0,MODERATE,201.0,180.0,201.0,1.52,68.0,...,44.09,4,2,0,2,1,0,0,1,0
3,4,145,56,60.0,VERY SEVERE,210.0,210.0,210.0,0.47,14.0,...,62.04,1,4,1,2,0,0,1,1,0
4,5,136,65,68.0,SEVERE,204.0,210.0,210.0,1.07,42.0,...,75.56,1,3,1,2,0,1,1,0,0

In [5]:
display(df.head())

,Unnamed: 0,ID,AGE,PackHistory,COPDSEVERITY,MWT1,MWT2,MWT1Best,FEV1,FEV1PRED,...,SGRQ,AGEquartiles,copd,gender,smoking,Diabetes,muscular,hypertension,AtrialFib,IHD
0,1,58,77,60.0,SEVERE,120.0,120.0,120.0,1.21,36.0,...,69.55,4,3,1,2,1,0,0,1,0
1,2,57,79,50.0,MODERATE,165.0,176.0,176.0,1.09,56.0,...,44.24,4,2,0,2,1,0,0,1,1
2,3,62,80,11.0,MODERATE,201.0,180.0,201.0,1.52,68.0,...,44.09,4,2,0,2,1,0,0,1,0
3,4,145,56,60.0,VERY SEVERE,210.0,210.0,210.0,0.47,14.0,...,62.04,1,4,1,2,0,0,1,1,0
4,5,136,65,68.0,SEVERE,204.0,210.0,210.0,1.07,42.0,...,75.56,1,3,1,2,0,1,1,0,0

In [6]:
import os

# Ver todos los archivos descargados en la carpeta
print(os.listdir(path))

['dataset.csv']

In [7]:
from google.colab import files
import os

# Ruta completa al archivo dataset.csv
csv_path = os.path.join(path, "dataset.csv")

# Descargar el archivo a tu PC
files.download(csv_path)

In [8]:
import os

# Mostrar los archivos descargados en la carpeta
print(os.listdir(path))

['dataset.csv']

In [9]:
import pandas as pd

Pulmo3 = pd.read_csv(os.path.join(path, "dataset.csv"))
print(Pulmo3.head())

   Unnamed: 0   ID  AGE  PackHistory COPDSEVERITY   MWT1   MWT2  MWT1Best  \
0           1   58   77         60.0       SEVERE  120.0  120.0     120.0
1           2   57   79         50.0     MODERATE  165.0  176.0     176.0
2           3   62   80         11.0     MODERATE  201.0  180.0     201.0
3           4  145   56         60.0  VERY SEVERE  210.0  210.0     210.0
4           5  136   65         68.0       SEVERE  204.0  210.0     210.0

   FEV1  FEV1PRED  ...   SGRQ  AGEquartiles  copd  gender  smoking  Diabetes  \
0  1.21      36.0  ...  69.55             4     3       1        2         1
1  1.09      56.0  ...  44.24             4     2       0        2         1
2  1.52      68.0  ...  44.09             4     2       0        2         1
3  0.47      14.0  ...  62.04             1     4       1        2         0
4  1.07      42.0  ...  75.56             1     3       1        2         0

   muscular  hypertension  AtrialFib  IHD
0         0             0          1    0
1         0             0          1    1
2         0             0          1    0
3         0             1          1    0
4         1             1          0    0

[5 rows x 24 columns]

In [10]:
Pulmo3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    101 non-null    int64
 1   ID            101 non-null    int64
 2   AGE           101 non-null    int64
 3   PackHistory   101 non-null    float64
 4   COPDSEVERITY  101 non-null    object
 5   MWT1          99 non-null     float64
 6   MWT2          100 non-null    float64
 7   MWT1Best      100 non-null    float64
 8   FEV1          101 non-null    float64
 9   FEV1PRED      101 non-null    float64
 10  FVC           101 non-null    float64
 11  FVCPRED       101 non-null    int64
 12  CAT           101 non-null    int64
 13  HAD           101 non-null    float64
 14  SGRQ          101 non-null    float64
 15  AGEquartiles  101 non-null    int64
 16  copd          101 non-null    int64
 17  gender        101 non-null    int64
 18  smoking       101 non-null    int64
 19  Diabetes      101 non-null    int64
 20  muscular      101 non-null    int64
 21  hypertension  101 non-null    int64
 22  AtrialFib     101 non-null    int64
 23  IHD           101 non-null    int64
dtypes: float64(9), int64(14), object(1)
memory usage: 19.1+ KB

In [11]:
# Contar cuántas filas duplicadas hay
print("Número de duplicados:", Pulmo3.duplicated().sum())

Número de duplicados: 0

In [12]:
Pulmo3.shape

(101, 24)

In [13]:
# Calcular la media de MWT1 (ignorando los nulos)
mean_mwt1 = Pulmo3["MWT1"].mean()

# Rellenar los valores faltantes con la media
Pulmo3["MWT1"] = Pulmo3["MWT1"].fillna(mean_mwt1)

# Verificar que ya no haya nulos
print("Nulos en MWT1 después de imputar:", Pulmo3["MWT1"].isnull().sum())

Nulos en MWT1 después de imputar: 0

In [14]:
# Calcular la media de MWT1 (ignorando los nulos)
mean_mwt1 = Pulmo3["MWT2"].mean()

# Rellenar los valores faltantes con la media
Pulmo3["MWT2"] = Pulmo3["MWT2"].fillna(mean_mwt1)

# Verificar que ya no haya nulos
print("Nulos en MWT2 después de imputar:", Pulmo3["MWT2"].isnull().sum())

Nulos en MWT2 después de imputar: 0

In [15]:
# Calcular la media de MWT1Best (ignorando los nulos)
mean_mwt1 = Pulmo3["MWT1Best"].mean()

# Rellenar los valores faltantes con la media
Pulmo3["MWT1Best"] = Pulmo3["MWT1Best"].fillna(mean_mwt1)

# Verificar que ya no haya nulos
print("Nulos en MWT1Best después de imputar:", Pulmo3["MWT1Best"].isnull().sum())

Nulos en MWT1Best después de imputar: 0

Normalizamos

In [16]:
# Valores únicos en la columna 'COPDSEVERITY'
print(Pulmo3["COPDSEVERITY"].unique())

['SEVERE' 'MODERATE' 'VERY SEVERE' 'MILD']

In [17]:
# One-Hot Encoding para COPDSEVERITY
Pulmo3 = pd.get_dummies(Pulmo3, columns=["COPDSEVERITY"], prefix="COPDSEVERITY")

# Convertir las nuevas columnas a enteros (0 y 1)
Pulmo3[Pulmo3.filter(like="COPDSEVERITY_").columns] = Pulmo3.filter(like="COPDSEVERITY_").astype(int)

# Verificar resultado
for col in Pulmo3.filter(like="COPDSEVERITY_").columns:
    print(col, Pulmo3[col].unique(), Pulmo3[col].dtype)

COPDSEVERITY_MILD [0 1] int64
COPDSEVERITY_MODERATE [0 1] int64
COPDSEVERITY_SEVERE [1 0] int64
COPDSEVERITY_VERY SEVERE [0 1] int64

In [18]:
Pulmo3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                101 non-null    int64
 1   ID                        101 non-null    int64
 2   AGE                       101 non-null    int64
 3   PackHistory               101 non-null    float64
 4   MWT1                      101 non-null    float64
 5   MWT2                      101 non-null    float64
 6   MWT1Best                  101 non-null    float64
 7   FEV1                      101 non-null    float64
 8   FEV1PRED                  101 non-null    float64
 9   FVC                       101 non-null    float64
 10  FVCPRED                   101 non-null    int64
 11  CAT                       101 non-null    int64
 12  HAD                       101 non-null    float64
 13  SGRQ                      101 non-null    float64
 14  AGEquartiles              101 non-null    int64
 15  copd                      101 non-null    int64
 16  gender                    101 non-null    int64
 17  smoking                   101 non-null    int64
 18  Diabetes                  101 non-null    int64
 19  muscular                  101 non-null    int64
 20  hypertension              101 non-null    int64
 21  AtrialFib                 101 non-null    int64
 22  IHD                       101 non-null    int64
 23  COPDSEVERITY_MILD         101 non-null    int64
 24  COPDSEVERITY_MODERATE     101 non-null    int64
 25  COPDSEVERITY_SEVERE       101 non-null    int64
 26  COPDSEVERITY_VERY SEVERE  101 non-null    int64
dtypes: float64(9), int64(18)
memory usage: 21.4 KB

In [19]:
# Guardar Pulmo1 en un archivo CSV
Pulmo3.to_csv("Pulmo3.csv", index=False)

print("Archivo Pulmo3.csv descargado correctamente")

Archivo Pulmo3.csv descargado correctamente

### Descripción de las Columnas del Dataset `Pulmo3`

A continuación, se presenta una descripción de cada columna en el DataFrame `Pulmo3`, basada en los nombres de las columnas y los tipos de datos observados.

| Columna                    | Tipo de Datos | Descripción                                                                                                                                                                             |
|:---------------------------|:--------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `Unnamed: 0`               | `int64`       | Columna de índice o un identificador de fila original, a menudo generada al guardar/cargar CSVs. Puede ser redundante.                                                                    |
| `ID`                       | `int64`       | Identificador único para cada paciente o registro.                                                                                                                                      |
| `AGE`                      | `int64`       | Edad del paciente en años.                                                                                                                                                              |
| `PackHistory`              | `float64`     | Historial de tabaquismo del paciente, posiblemente en paquetes-año (packs-years).                                                                                                       |
| `MWT1`                     | `float64`     | Distancia caminada en la primera prueba de marcha de 6 minutos (6MWT).                                                                                                                    |
| `MWT2`                     | `float64`     | Distancia caminada en la segunda prueba de marcha de 6 minutos (6MWT).                                                                                                                   |
| `MWT1Best`                 | `float64`     | La mejor distancia caminada entre MWT1 y MWT2.                                                                                                                                          |
| `FEV1`                     | `float64`     | Volumen espiratorio forzado en 1 segundo (medida de función pulmonar).                                                                                                                  |
| `FEV1PRED`                 | `float64`     | Porcentaje predicho de FEV1 (FEV1 como porcentaje del valor esperado).                                                                                                                  |
| `FVC`                      | `float64`     | Capacidad vital forzada (medida de función pulmonar).                                                                                                                                   |
| `FVCPRED`                  | `int64`       | Porcentaje predicho de FVC (FVC como porcentaje del valor esperado).                                                                                                                    |
| `CAT`                      | `int64`       | Puntuación del Cuestionario de Evaluación de la EPOC (CAT score), mide el impacto de la EPOC en la vida del paciente.                                                                    |
| `HAD`                      | `float64`     | Puntuación de la Escala de Ansiedad y Depresión Hospitalaria (Hospital Anxiety and Depression scale).                                                                                    |
| `SGRQ`                     | `float64`     | Puntuación del Cuestionario Respiratorio de St. George (St. George's Respiratory Questionnaire), evalúa el estado de salud de los pacientes con enfermedades respiratorias.                 |
| `AGEquartiles`             | `int64`       | Cuartil de edad del paciente.                                                                                                                                                           |
| `copd`                     | `int64`       | Indicador numérico de la presencia o gravedad de la EPOC.                                                                                                                               |
| `gender`                   | `int64`       | Género del paciente (e.g., 0 para femenino, 1 para masculino).                                                                                                                          |
| `smoking`                  | `int64`       | Estado de fumador del paciente (e.g., 0 para no fumador, 1 para ex-fumador, 2 para fumador actual).                                                                                     |
| `Diabetes`                 | `int64`       | Indicador de si el paciente tiene diabetes (e.g., 0 para no, 1 para sí).                                                                                                                |
| `muscular`                 | `int64`       | Indicador de si el paciente tiene alguna condición muscular (e.g., 0 para no, 1 para sí).                                                                                               |
| `hypertension`             | `int64`       | Indicador de si el paciente tiene hipertensión (e.g., 0 para no, 1 para sí).                                                                                                            |
| `AtrialFib`                | `int64`       | Indicador de si el paciente tiene fibrilación auricular (e.g., 0 para no, 1 para sí).                                                                                                   |
| `IHD`                      | `int64`       | Indicador de si el paciente tiene enfermedad isquémica del corazón (e.g., 0 para no, 1 para sí).                                                                                        |
| `COPDSEVERITY_MILD`        | `int64`       | Columna dummy: 1 si la severidad de EPOC es MILD, 0 en otro caso.                                                                                                                       |
| `COPDSEVERITY_MODERATE`    | `int64`       | Columna dummy: 1 si la severidad de EPOC es MODERATE, 0 en otro caso.                                                                                                                   |
| `COPDSEVERITY_SEVERE`      | `int64`       | Columna dummy: 1 si la severidad de EPOC es SEVERE, 0 en otro caso.                                                                                                                     |
| `COPDSEVERITY_VERY SEVERE` | `int64`       | Columna dummy: 1 si la severidad de EPOC es VERY SEVERE, 0 en otro caso.                                                                                                                |