In [2]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import matplotlib as plt

import seaborn as sns

Liver2

Aqui estamos trabajando con https://archive.ics.uci.edu/dataset/878/cirrhosis+patient+survival+prediction+dataset-1

In [3]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.12/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.3)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.7.22)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [4]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
cirrhosis_patient_survival_prediction = fetch_ucirepo(id=878)

# data (as pandas dataframes)
X = cirrhosis_patient_survival_prediction.data.features
y = cirrhosis_patient_survival_prediction.data.targets

# metadata
print(cirrhosis_patient_survival_prediction.metadata)

# variable information
print(cirrhosis_patient_survival_prediction.variables)

{'uci_id': 878, 'name': 'Cirrhosis Patient Survival Prediction', 'repository_url': 'https://archive.ics.uci.edu/dataset/878/cirrhosis+patient+survival+prediction+dataset-1', 'data_url': 'https://archive.ics.uci.edu/static/public/878/data.csv', 'abstract': 'Utilize 17 clinical features for predicting survival state of patients with liver cirrhosis. The survival states include 0 = D (death), 1 = C (censored), 2 = CL (censored due to liver transplantation).', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 418, 'num_features': 17, 'feature_types': ['Real', 'Categorical'], 'demographics': ['Age', 'Sex'], 'target_col': ['Status'], 'index_col': ['ID'], 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1989, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C5R02G', 'creators': ['E. Dickson', 'P. Grambsch', 'T. Fleming', 'L. Fisher', 'A. Langworthy'], 'intro_paper': {'ID': 296, 'type': 'NATIVE', 'title': 'Prognosis in primary biliary cirrhosis: Model for decision making', 'authors': 'E. Dickson, P. Grambsch, T. Fleming, L. Fisher, A. Langworthy', 'venue': 'Hepatology', 'year': 1989, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/db1487216b8a4b26f5e5078ea9109ac9d8355b65', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "During 1974 to 1984, 424 PBC patients referred to the Mayo Clinic qualified for the randomized placebo-controlled trial testing the drug D-penicillamine. Of these, the initial 312 patients took part in the trial and have mostly comprehensive data. The remaining 112 patients didn't join the clinical trial but agreed to record basic metrics and undergo survival tracking. Six of these patients were soon untraceable after their diagnosis, leaving data for 106 of these individuals in addition to the 312 who were part of the randomized trial.", 'purpose': 'Cirrhosis results from prolonged liver damage, leading to extensive scarring, often due to conditions like hepatitis or chronic alcohol consumption. The data provided is sourced from a Mayo Clinic study on primary biliary cirrhosis (PBC) of the liver carried out from 1974 to 1984.', 'funded_by': 'Mayo Clinic', 'instances_represent': 'People', 'recommended_data_splits': None, 'sensitive_data': 'Gender, Age', 'preprocessing_description': '1. Drop all the rows where miss value (NA) were present in the Drug column\n2. Impute missing values with mean results\n3. One-hot encoding for all category attributes', 'variable_info': '1. ID: unique identifier\n2. N_Days: number of days between registration and the earlier of death, transplantation, or study analysis time in July 1986\n3. Status: status of the patient C (censored), CL (censored due to liver tx), or D (death)\n4. Drug: type of drug D-penicillamine or placebo\n5. Age: age in [days]\n6. Sex: M (male) or F (female)\n7. Ascites: presence of ascites N (No) or Y (Yes)\n8. Hepatomegaly: presence of hepatomegaly N (No) or Y (Yes)\n9. Spiders: presence of spiders N (No) or Y (Yes)\n10. Edema: presence of edema N (no edema and no diuretic therapy for edema), S (edema present without diuretics, or edema resolved by diuretics), or Y (edema despite diuretic therapy)\n11. Bilirubin: serum bilirubin in [mg/dl]\n12. Cholesterol: serum cholesterol in [mg/dl]\n13. Albumin: albumin in [gm/dl]\n14. Copper: urine copper in [ug/day]\n15. Alk_Phos: alkaline phosphatase in [U/liter]\n16. SGOT: SGOT in [U/ml]\n17. Triglycerides: triglicerides in [mg/dl]\n18. Platelets: platelets per cubic [ml/1000]\n19. Prothrombin: prothrombin time in seconds [s]\n20. Stage: histologic stage of disease (1, 2, 3, or 4)\n', 'citation': 'Fleming, Thomas R., and David P. Harrington. Counting processes and survival analysis. Vol. 625. John Wiley & Sons, 2013.'}}
             name     role         type demographic  \
0              ID       ID      Integer        None
1          N_Days    Other      Integer        None
2          Status   Target  Categorical        None
3            Drug  Feature  Categorical        None
4             Age  Feature      Integer         Age
5             Sex  Feature  Categorical         Sex
6         Ascites  Feature  Categorical        None
7    Hepatomegaly  Feature  Categorical        None
8         Spiders  Feature  Categorical        None
9           Edema  Feature  Categorical        None
10      Bilirubin  Feature   Continuous        None
11    Cholesterol  Feature      Integer        None
12        Albumin  Feature   Continuous        None
13         Copper  Feature      Integer        None
14       Alk_Phos  Feature   Continuous        None
15           SGOT  Feature   Continuous        None
16  Tryglicerides  Feature      Integer        None
17      Platelets  Feature      Integer        None
18    Prothrombin  Feature   Continuous        None
19          Stage  Feature  Categorical        None

                                          description    units missing_values
0                                   unique identifier     None             no
1   number of days between registration and the ea...     None             no
2   status of the patient C (censored), CL (censor...     None             no
3             type of drug D-penicillamine or placebo     None            yes
4                                                 age     days             no
5                              M (male) or F (female)     None             no
6               presence of ascites N (No) or Y (Yes)     None            yes
7          presence of hepatomegaly N (No) or Y (Yes)     None            yes
8               presence of spiders N (No) or Y (Yes)     None            yes
9   presence of edema N (no edema and no diuretic ...     None             no
10                                    serum bilirubin    mg/dl             no
11                                  serum cholesterol    mg/dl            yes
12                                            albumin    gm/dl             no
13                                       urine copper   ug/day            yes
14                               alkaline phosphatase  U/liter            yes
15                                               SGOT     U/ml            yes
16                                      tryglicerides     None            yes
17                                platelets per cubic  ml/1000            yes
18                                   prothrombin time        s            yes
19        histologic stage of disease (1, 2, 3, or 4)     None            yes

In [5]:
import pandas as pd

# Concatenate features (X) and target (y) into a single DataFrame
df_full = pd.concat([X, y], axis=1)

# Display the first few rows of the combined DataFrame
display(df_full.head())

,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
0,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261,2.60,156,1718.0,137.95,172,190,12.2,4.0,D
1,D-penicillamine,20617,F,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6,3.0,C
2,D-penicillamine,25594,M,N,N,N,S,1.4,176,3.48,210,516.0,96.10,55,151,12.0,4.0,D
3,D-penicillamine,19994,F,N,Y,Y,S,1.8,244,2.54,64,6121.8,60.63,92,183,10.3,4.0,D
4,Placebo,13918,F,N,Y,Y,N,3.4,279,3.53,143,671.0,113.15,72,136,10.9,3.0,CL

In [6]:
# Save the combined DataFrame to a CSV file
df_full.to_csv('cirrhosis_patient_data.csv', index=False)

print('Data saved to cirrhosis_patient_data.csv')

Data saved to cirrhosis_patient_data.csv

Asigamos nombre al dataset

In [7]:
# Cargar la base de datos en la variable Liver2
Liver2 = pd.read_csv("cirrhosis_patient_data.csv")

# Ver las primeras filas para confirmar
print(Liver2.head())

              Drug    Age Sex Ascites Hepatomegaly Spiders Edema  Bilirubin  \
0  D-penicillamine  21464   F       Y            Y       Y     Y       14.5
1  D-penicillamine  20617   F       N            Y       Y     N        1.1
2  D-penicillamine  25594   M       N            N       N     S        1.4
3  D-penicillamine  19994   F       N            Y       Y     S        1.8
4          Placebo  13918   F       N            Y       Y     N        3.4

  Cholesterol  Albumin Copper  Alk_Phos    SGOT Tryglicerides Platelets  \
0         261     2.60    156    1718.0  137.95           172       190
1         302     4.14     54    7394.8  113.52            88       221
2         176     3.48    210     516.0   96.10            55       151
3         244     2.54     64    6121.8   60.63            92       183
4         279     3.53    143     671.0  113.15            72       136

   Prothrombin  Stage Status
0         12.2    4.0      D
1         10.6    3.0      C
2         12.0    4.0      D
3         10.3    4.0      D
4         10.9    3.0     CL

In [8]:
Liver2.shape

(418, 18)

In [9]:
Liver2.head

<bound method NDFrame.head of                 Drug    Age Sex Ascites Hepatomegaly Spiders Edema  Bilirubin  \
0    D-penicillamine  21464   F       Y            Y       Y     Y       14.5
1    D-penicillamine  20617   F       N            Y       Y     N        1.1
2    D-penicillamine  25594   M       N            N       N     S        1.4
3    D-penicillamine  19994   F       N            Y       Y     S        1.8
4            Placebo  13918   F       N            Y       Y     N        3.4
..               ...    ...  ..     ...          ...     ...   ...        ...
413              NaN  24472   F     NaN          NaN     NaN     N        1.2
414              NaN  14245   F     NaN          NaN     NaN     N        0.9
415              NaN  20819   F     NaN          NaN     NaN     N        1.6
416              NaN  21185   F     NaN          NaN     NaN     N        0.8
417              NaN  19358   F     NaN          NaN     NaN     N        0.7

    Cholesterol  Albumin Copper  Alk_Phos    SGOT Tryglicerides Platelets  \
0           261     2.60    156    1718.0  137.95           172       190
1           302     4.14     54    7394.8  113.52            88       221
2           176     3.48    210     516.0   96.10            55       151
3           244     2.54     64    6121.8   60.63            92       183
4           279     3.53    143     671.0  113.15            72       136
..          ...      ...    ...       ...     ...           ...       ...
413         NaN     2.96    NaN       NaN     NaN           NaN       174
414         NaN     3.83    NaN       NaN     NaN           NaN       180
415         NaN     3.42    NaN       NaN     NaN           NaN       143
416         NaN     3.75    NaN       NaN     NaN           NaN       269
417         NaN     3.29    NaN       NaN     NaN           NaN       350

     Prothrombin  Stage Status
0           12.2    4.0      D
1           10.6    3.0      C
2           12.0    4.0      D
3           10.3    4.0      D
4           10.9    3.0     CL
..           ...    ...    ...
413         10.9    3.0      D
414         11.2    4.0      C
415          9.9    3.0      C
416         10.4    3.0      C
417         10.6    4.0      C

[418 rows x 18 columns]>

Veamos si hay datos faltantes

In [10]:
Liver2.isnull().sum()

Drug             105
Age                0
Sex                0
Ascites          105
Hepatomegaly     105
Spiders          105
Edema              0
Bilirubin          0
Cholesterol      106
Albumin            0
Copper           106
Alk_Phos         106
SGOT             106
Tryglicerides    106
Platelets          7
Prothrombin        2
Stage              6
Status             0
dtype: int64

In [11]:
Liver2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Drug           313 non-null    object
 1   Age            418 non-null    int64
 2   Sex            418 non-null    object
 3   Ascites        313 non-null    object
 4   Hepatomegaly   313 non-null    object
 5   Spiders        313 non-null    object
 6   Edema          418 non-null    object
 7   Bilirubin      418 non-null    float64
 8   Cholesterol    312 non-null    object
 9   Albumin        418 non-null    float64
 10  Copper         312 non-null    object
 11  Alk_Phos       312 non-null    float64
 12  SGOT           312 non-null    float64
 13  Tryglicerides  312 non-null    object
 14  Platelets      411 non-null    object
 15  Prothrombin    416 non-null    float64
 16  Stage          412 non-null    float64
 17  Status         418 non-null    object
dtypes: float64(6), int64(1), object(11)
memory usage: 58.9+ KB

Cambiamos las variables de object a int64

In [12]:
#veamos los datos que tiene Drug
Liver2['Drug'].unique()

array(['D-penicillamine', 'Placebo', 'NaNN', nan], dtype=object)

Dejamos la columna Drug con solo 3 variables, convirtiendo NaNN en nan

In [13]:
# Reemplazar el texto "NaNN" por un verdadero NaN
Liver2["Drug"] = Liver2["Drug"].replace("NaNN", np.nan)

# Verificar los valores únicos después de la limpieza
print(Liver2["Drug"].unique())

['D-penicillamine' 'Placebo' nan]

Aplicamos one-hot encoding a Drug

In [14]:
# Normalizar valores nulos
Liver2["Drug"] = Liver2["Drug"].replace("NaNN", np.nan)

# Crear columnas binarias
Liver2["Drug_Dpenicillamine"] = (Liver2["Drug"] == "D-penicillamine").astype(int)
Liver2["Drug_Placebo"] = (Liver2["Drug"] == "Placebo").astype(int)
Liver2["Drug_NA"] = Liver2["Drug"].isna().astype(int)

# Verificar tipos de datos
print(Liver2[["Drug_Dpenicillamine", "Drug_Placebo", "Drug_NA"]].dtypes)

Drug_Dpenicillamine    int64
Drug_Placebo           int64
Drug_NA                int64
dtype: object

Para la siguiente columna no conviene usar media ni mediana, porque son medidas numéricas y aquí hablamos de una variable categórica binaria, si usamos modas podriamos imputar y crear sesgos

In [15]:
# Normalizar valores nulos
Liver2["Ascites"] = Liver2["Ascites"].replace("NaNN", np.nan)

# Codificación binaria
Liver2["Ascites"] = Liver2["Ascites"].map({"Y": 1, "N": 0})

# Columna indicadora de nulos
Liver2["Ascites_NA"] = Liver2["Ascites"].isna().astype(int)

# Verificar
print(Liver2[["Ascites", "Ascites_NA"]].head())

   Ascites  Ascites_NA
0      1.0           0
1      0.0           0
2      0.0           0
3      0.0           0
4      0.0           0

In [26]:
Liver2[Trygliserides].info()

NameError: name 'Trygliserides' is not defined

In [16]:
Liver2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Drug                 312 non-null    object
 1   Age                  418 non-null    int64
 2   Sex                  418 non-null    object
 3   Ascites              312 non-null    float64
 4   Hepatomegaly         313 non-null    object
 5   Spiders              313 non-null    object
 6   Edema                418 non-null    object
 7   Bilirubin            418 non-null    float64
 8   Cholesterol          312 non-null    object
 9   Albumin              418 non-null    float64
 10  Copper               312 non-null    object
 11  Alk_Phos             312 non-null    float64
 12  SGOT                 312 non-null    float64
 13  Tryglicerides        312 non-null    object
 14  Platelets            411 non-null    object
 15  Prothrombin          416 non-null    float64
 16  Stage                412 non-null    float64
 17  Status               418 non-null    object
 18  Drug_Dpenicillamine  418 non-null    int64
 19  Drug_Placebo         418 non-null    int64
 20  Drug_NA              418 non-null    int64
 21  Ascites_NA           418 non-null    int64
dtypes: float64(7), int64(5), object(10)
memory usage: 72.0+ KB

Aplicamos el mismo criterio a la columna Hepatomegaly que usamos anteriormente para Ascites

In [17]:
# Normalizar valores nulos
Liver2["Hepatomegaly"] = Liver2["Hepatomegaly"].replace("NaNN", np.nan)

# Codificación binaria
Liver2["Hepatomegaly"] = Liver2["Hepatomegaly"].map({"Y": 1, "N": 0})

# Columna indicadora de nulos
Liver2["Hepatomegaly_NA"] = Liver2["Hepatomegaly"].isna().astype(int)

# Verificar
print(Liver2[["Hepatomegaly", "Hepatomegaly_NA"]].head())

   Hepatomegaly  Hepatomegaly_NA
0           1.0                0
1           1.0                0
2           0.0                0
3           1.0                0
4           1.0                0

Aplicamos el mismo criterio para Spider

In [18]:
# Normalizar valores nulos
Liver2["Spiders"] = Liver2["Spiders"].replace("NaNN", np.nan)

# Codificación binaria
Liver2["Spiders"] = Liver2["Spiders"].map({"Y": 1, "N": 0})

# Columna indicadora de nulos
Liver2["Spiders_NA"] = Liver2["Spiders"].isna().astype(int)

# Verificar
print(Liver2[["Spiders", "Spiders_NA"]].head())

   Spiders  Spiders_NA
0      1.0           0
1      1.0           0
2      0.0           0
3      1.0           0
4      1.0           0

Vamos con Cholesterol

In [19]:
Liver2["Cholesterol"].unique()

array(['261', '302', '176', '244', '279', '248', '322', '280', '562',
       '200', '259', '236', '281', 'NaNN', '231', '204', '274', '178',
       '235', '374', '252', '271', '395', '456', '298', '1128', '175',
       '222', '370', '260', '296', '262', '210', '364', '314', '172',
       '334', '383', '282', '361', '299', '482', '316', '257', '276',
       '614', '288', '416', '498', '242', '329', '604', '216', '932',
       '373', '256', '427', '466', '174', '652', '258', '320', '132',
       '558', '674', '394', '436', '315', '247', '448', '472', '250',
       '263', '1600', '345', '408', '660', '325', '206', '353', '201',
       '420', '239', '460', '400', '188', '303', '464', '212', '127',
       '120', '486', '528', '267', '458', '950', '390', '636', '151',
       '251', '269', '268', '1775', '331', '578', '399', '426', '328',
       '290', '346', '332', '556', '309', '1015', '586', '217', '168',
       '220', '358', '286', '450', '317', '502', '233', '196', '1480',
       '376', '205', '283', '396', '478', '225', '808', '187', '360',
       '1092', '308', '293', '347', '226', '266', '392', '223', '149',
       '255', '382', '213', '232', '404', '1276', '608', '215', '372',
       '191', '518', '514', '1336', '253', '442', '300', '354', '468',
       '350', '273', '387', '1712', '324', '227', '246', '243', '193',
       '336', '414', '277', '375', '432', '356', '348', '318', '344',
       '321', '572', '219', '338', '198', '304', '412', '291', '310',
       '294', '339', '546', '194', '1000', '646', '275', '340', '342',
       '393', '335', '434', '576', nan], dtype=object)

En este caso vemos mas recomendable usar la mediana porque no se ve afectada por valores extremos y refleja mejor el valor central de la distribución

In [20]:
# Convertir a numérico
Liver2["Cholesterol"] = pd.to_numeric(Liver2["Cholesterol"], errors="coerce")

# Calcular la mediana
mediana_chol = Liver2["Cholesterol"].median()

# Imputar valores faltantes con la mediana
Liver2["Cholesterol"] = Liver2["Cholesterol"].fillna(mediana_chol)

# Verificar que ya no haya NaN
print(Liver2["Cholesterol"].isna().sum())

0

Copper aplicamos el mismo criterio que en Cholesterol

In [21]:
Liver2["Copper"].unique()

array(['156', '54', '210', '64', '143', '50', '52', '79', '140', '46',
       '94', '40', '43', '173', '28', '159', '588', '39', '41', '464',
       '558', '124', '53', '221', '209', '24', '172', '114', '101', '82',
       '37', '201', '18', '150', '102', '105', '96', '122', '36', '131',
       '19', '161', '68', '281', '58', '158', '262', '121', '88', '231',
       '73', '49', '95', '74', '84', '20', '51', '17', '280', '207',
       '111', '199', '75', '13', '269', '34', '154', '48', '29', '110',
       '178', '182', '33', '62', '77', '148', '145', '31', '57', '38',
       '10', '14', '89', '103', '208', '81', '67', '129', '444', '25',
       'NaNN', '9', '42', '30', '205', '60', '35', '123', '27', '59',
       '86', '152', '32', '247', '290', '243', '225', '219', '217', '4',
       '91', '80', '200', '44', '65', '76', '63', '358', '251', '233',
       '267', '112', '26', '15', '227', '23', '108', '12', '11', '141',
       '72', '115', '47', '412', '78', '71', '308', '139', '116', '380',
       '188', '45', '138', '16', '22', '136', '130', '69', '220', '97',
       '70', '155', '107', '177', '196', '100', '90', '234', '186', nan],
      dtype=object)

In [22]:
# Convertir a numérico
Liver2["Copper"] = pd.to_numeric(Liver2["Copper"], errors="coerce")

# Calcular la mediana
mediana_copper = Liver2["Copper"].median()

# Imputar valores faltantes con la mediana
Liver2["Copper"] = Liver2["Copper"].fillna(mediana_copper)

# (Opcional) Crear columna indicadora de nulos originales
Liver2["Copper_NA"] = Liver2["Copper"].isna().astype(int)

# Verificar
print(Liver2[["Copper", "Copper_NA"]].head())

   Copper  Copper_NA
0   156.0          0
1    54.0          0
2   210.0          0
3    64.0          0
4   143.0          0

Para imputar valores faltantes, la mediana es más recomendable que la media, porque esta variable suele tener valores extremos (outliers) en pacientes con enfermedad hepática.

In [23]:
# Calcular la media
media_alk = Liver2["Alk_Phos"].mean()

# Imputar valores faltantes con la media
Liver2["Alk_Phos"] = Liver2["Alk_Phos"].fillna(media_alk)

# Verificar que ya no haya NaN
print(Liver2["Alk_Phos"].isna().sum())

0

In [24]:
Liver2["SGOT"].unique()

array([137.95, 113.52,  96.1 ,  60.63, 113.15,  93.  ,  60.45,  28.38,
       144.15, 147.25,  79.05,  82.15,  88.35,  71.  , 127.71,  72.85,
       117.8 , 280.55, 122.45,  65.1 , 120.9 , 227.04, 221.88, 106.95,
       165.85, 101.91, 189.1 ,  73.53, 121.26, 206.4 ,  82.56, 218.55,
       170.5 ,  72.24,  71.3 , 180.6 , 104.49, 151.9 ,  56.76,  67.08,
       119.35, 136.74, 187.55, 188.34,  97.65,  99.33,  79.98,  95.46,
       105.78, 126.42,  43.4 , 244.9 , 150.35, 141.05, 182.9 , 328.6 ,
       215.45,  54.25,  49.6 ,  89.9 , 155.  , 176.7 ,  80.6 , 110.05,
       246.45,  86.8 , 232.5 , 159.65,  99.2 ,  77.5 , 108.5 , 178.25,
       164.3 ,  62.  , 128.65, 103.85, 172.05, 196.85, 111.6 , 130.2 ,
        46.5 , 179.8 ,  57.35, 299.15, 136.4 , 127.1 ,  74.4 , 116.25,
       145.7 ,  94.55, 186.  , 125.55, 134.85, 198.4 ,  41.85, 173.6 ,
       102.3 ,  85.25, 114.7 , 153.45, 201.5 ,  75.95,  66.65, 181.35,
       133.3 , 457.25,  83.7 , 142.6 ,  91.45, 139.5 , 237.15,  26.35,
       167.4 ,  69.75,  51.15, 161.2 , 221.65, 184.45,  52.7 , 238.7 ,
       100.75, 203.05,  55.8 , 210.8 , 134.  , 158.1 , 175.15, 105.4 ,
       209.25, 272.8 , 220.1 ,  83.  , 110.  ,  53.  ,  84.  ,  56.  ,
        99.  , 125.  ,  98.  ,  89.  ,  91.  , 190.  ,  92.  , 120.  ,
        70.  , 106.  ,  82.  , 188.  , 111.  ,  58.  ,  87.  , 128.  ,
       145.  , 185.  ,  57.  , 142.  , 338.  ,  85.  , 122.  , 117.  ,
        86.  , 205.  , 127.  , 163.  , 193.  , 137.  ,  75.  ,  97.  ,
       150.  , 135.  ,  74.  ,  52.  , 140.  ,  45.  , 288.  ,  55.  ,
       130.  , 171.  , 136.  ,    nan])

Agregamos una columna extra para datos Na, para SGOT

In [25]:
# Convertir SGOT a numérico
Liver2["SGOT"] = pd.to_numeric(Liver2["SGOT"], errors="coerce")


# Dejar nulos y crear columna indicadora
Liver2["SGOT_NA"] = Liver2["SGOT"].isna().astype(int)

# Verificar
print(Liver2[["SGOT", "SGOT_NA"]].head())

     SGOT  SGOT_NA
0  137.95        0
1  113.52        0
2   96.10        0
3   60.63        0
4  113.15        0

In [28]:
Liver2["Tryglicerides"].unique()

array(['172', '88', '55', '92', '72', '63', '213', '189', '143', '79',
       '95', '130', 'NaNN', '96', '58', '128', '200', '123', '135', '83',
       '191', '230', '66', '166', '168', '195', '86', '158', '101', '113',
       '64', '151', '118', '87', '111', '89', '50', '165', '71', '178',
       '73', '93', '125', '219', '319', '94', '124', '188', '112', '133',
       '108', '171', '185', '46', '184', '76', '80', '56', '309', '598',
       '243', '91', '104', '70', '318', '272', '100', '74', '84', '174',
       '98', '155', '68', '69', '122', '102', '53', '77', '52', '109',
       '78', '90', '156', '382', '149', '114', '210', '49', '85', '107',
       '137', '232', '97', '175', '99', '105', '121', '152', '218', '134',
       '146', '103', '106', '280', '126', '75', '205', '206', '140',
       '119', '180', '142', '154', '110', '145', '62', '164', '432',
       '157', '194', '67', '57', '131', '224', '44', '177', '81', '139',
       '322', '231', '214', '33', '120', '209', '260', '179', '117',
       '116', '193', '229', '169', '242', '153', '127', '144', '59', '82',
       nan], dtype=object)

Usamos el mismo criterio para Tryglicerides

In [29]:
# Convertir Tryglicerides a numérico
Liver2["Tryglicerides"] = pd.to_numeric(Liver2["Tryglicerides"], errors="coerce")

# Crear columna indicadora de nulos originales
Liver2["Tryglicerides_NA"] = Liver2["Tryglicerides"].isna().astype(int)

# Verificar
print(Liver2[["Tryglicerides", "Tryglicerides_NA"]].head())

   Tryglicerides  Tryglicerides_NA
0          172.0                 0
1           88.0                 0
2           55.0                 0
3           92.0                 0
4           72.0                 0

In [30]:
Liver2["Platelets"].unique()

array(['190', '221', '151', '183', '136', 'NaNN', '204', '373', '251',
       '302', '258', '71', '244', '156', '295', '198', '224', '283',
       '209', '322', '336', '173', '214', '70', '324', '421', '80', '144',
       '390', '124', '195', '286', '180', '273', '431', '311', '102',
       '234', '563', '358', '226', '344', '203', '199', '474', '518',
       '356', '233', '128', '362', '254', '213', '365', '216', '321',
       '228', '211', '329', '165', '178', '430', '123', '261', '227',
       '265', '410', '225', '278', '268', '132', '236', '426', '360',
       '385', '412', '81', '181', '447', '442', '200', '337', '145',
       '380', '188', '401', '338', '312', '172', '119', '327', '110',
       '349', '348', '137', '316', '334', '271', '141', '467', '266',
       '307', '438', '354', '207', '306', '256', '104', '182', '238',
       '166', '453', '418', '121', '427', '445', '206', '252', '142',
       '318', '277', '335', '253', '239', '330', '140', '301', '339',
       '270', '108', '487', '313', '269', '160', '88', '212', '263',
       '361', '217', '493', '340', '149', '325', '175', '79', '539',
       '471', '192', '164', '399', '382', '129', '117', '201', '381',
       '328', '332', '514', '281', '126', '240', '259', '309', '298',
       '114', '223', '146', '423', '176', '210', '231', '394', '139',
       '95', '284', '341', '319', '326', '282', '305', '185', '297',
       '371', '303', '249', '317', '97', '264', '242', '248', '375',
       '296', '279', '289', '153', '202', '372', '215', '280', '62',
       '255', '422', '143', '304', '291', '122', '299', '293', '243',
       '246', '275', '288', '378', '331', nan, '260', '130', '721', '155',
       '475', '388', '191', '150', '167', '125', '171', '109', '314',
       '419', '517', '432', '384', '274', '292', '92', '76', '120', '402',
       '425', '189', '193', '219', '220', '162', '174', '350'],
      dtype=object)

En este caso, la media es aceptable porque los datos están casi completos y los pocos nulos no afectarán demasiado.

In [31]:
# Convertir a numérico
Liver2["Platelets"] = pd.to_numeric(Liver2["Platelets"], errors="coerce")

# Calcular la media
media_platelets = Liver2["Platelets"].mean()

# Imputar valores faltantes con la media
Liver2["Platelets"] = Liver2["Platelets"].fillna(media_platelets)

# Verificar
print(Liver2["Platelets"].head())

0    190.0
1    221.0
2    151.0
3    183.0
4    136.0
Name: Platelets, dtype: float64

En este caso, la mediana sigue siendo más robusta, pero la diferencia con la media será mínima porque los nulos son casi inexistentes.

In [32]:
# Convertir a numérico
Liver2["Prothrombin"] = pd.to_numeric(Liver2["Prothrombin"], errors="coerce")

# Calcular la mediana
mediana_prot = Liver2["Prothrombin"].median()

# Imputar valores faltantes con la mediana
Liver2["Prothrombin"] = Liver2["Prothrombin"].fillna(mediana_prot)

# Verificar
print(Liver2["Prothrombin"].head())

0    12.2
1    10.6
2    12.0
3    10.3
4    10.9
Name: Prothrombin, dtype: float64

In [34]:
Liver2["Stage"].unique()

array([ 4.,  3.,  2.,  1., nan])

Como los faltantes son muy pocos, imputar con la mediana es seguro y no distorsiona la distribución.

In [35]:
# Convertir a numérico si aparece como object
Liver2["Stage"] = pd.to_numeric(Liver2["Stage"], errors="coerce")

# Calcular la mediana
mediana_stage = Liver2["Stage"].median()

# Imputar valores faltantes con la mediana
Liver2["Stage"] = Liver2["Stage"].fillna(mediana_stage)

# Verificar
print(Liver2["Stage"].head())

0    4.0
1    3.0
2    4.0
3    4.0
4    3.0
Name: Stage, dtype: float64

## Tabla de Descripción de Columnas

| Nombre de la Columna | Descripción                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|:---------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Drug**             | Tipo de fármaco administrado: `0` para D-penicilamina, `1` para Placebo, `2` para Desconocido.                                                                                                                                                                                                                                                                                                                                                                                                  |
| **Age**              | Edad del paciente en días.                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| **Sex**              | Género del paciente: `M` para masculino o `F` para femenino.                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| **Ascites**          | Presencia de ascitis: `N` para No o `Y` para Sí.                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| **Hepatomegaly**     | Presencia de hepatomegalia: `N` para No o `Y` para Sí.                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| **Spiders**          | Presencia de angiomas aracniformes (spiders): `N` para No o `Y` para Sí.                                                                                                                                                                                                                                                                                                                                                                                                                          |
| **Edema**            | Presencia de edema: `N` (sin edema y sin terapia diurética para el edema), `S` (edema presente sin diuréticos, o edema resuelto por diuréticos), o `Y` (edema a pesar de la terapia diurética).                                                                                                                                                                                                                                                                                              |
| **Bilirubin**        | Bilirrubina sérica en mg/dl.                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| **Cholesterol**      | Colesterol sérico en mg/dl.                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| **Albumin**          | Albúmina en gm/dl.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| **Copper**           | Cobre en orina en ug/día.                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| **Alk_Phos**         | Fosfatasa alcalina en U/litro.                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| **SGOT**             | SGOT en U/ml.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| **Tryglicerides**    | Triglicéridos en mg/dl.                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| **Platelets**        | Plaquetas por milímetro cúbico/1000.                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **Prothrombin**      | Tiempo de protrombina en segundos.                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| **Stage**            | Etapa histológica de la enfermedad (1, 2, 3 o 4).                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| **Status**           | Estado del paciente: `C` (censurado), `CL` (censurado debido a trasplante de hígado), o `D` (muerte).                                                                                                                                                                                                                                                                                                                                                                                             |

In [36]:
# Guardar el DataFrame Liver2 a un archivo CSV
Liver2.to_csv('Liver2_processed_data.csv', index=False)
print('DataFrame Liver2 guardado en Liver2_processed_data.csv')

DataFrame Liver2 guardado en Liver2_processed_data.csv