Aqui trabajamos con https://www.kaggle.com/datasets/sunilsah905/non-alcoholic-fatty-liver-disease/data

In [1]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import matplotlib as plt

import seaborn as sns

In [12]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sunilsah905/non-alcoholic-fatty-liver-disease")

print("Path to dataset files:", path)

Path to dataset files: /root/.cache/kagglehub/datasets/sunilsah905/non-alcoholic-fatty-liver-disease/versions/1

In [13]:
Liver3 = pd.read_csv("NAFLD_cleaned.csv")

In [14]:
# Verificar primeras filas
print(Liver3.head())

   Patient No.  Age  Gender (Female=1, Male=2)  Height  Weight  \
0            1   60                          1     150      80
1            2   55                          1     154      73
2            3   53                          2     170     101
3            4   33                          2     175      95
4            5   23                          2     162      68

   Body Mass Index  Waist Circumference  Hip Circumference  \
0            35.56                119.0              104.0
1            30.78                101.0               98.0
2            34.95                116.0              112.0
3            31.02                114.0              114.0
4            25.91                101.0               97.0

   Systolic Blood Pressure  Diastolic Blood Pressure  ...  Activity  Fibrosis  \
0                      135                        77  ...         2         1
1                      120                        72  ...         2         0
2                      120                        80  ...         2         3
3                      124                        83  ...         2         1
4                      124                        79  ...         2         0

   NAS score according to Kleiner  \
0                               4
1                               4
2                               4
3                               4
4                               4

   NAS score>=4 and Fibrosis>=2 (If NAS score>=4 and Fibrosis>=2 = 1, If not = 0)  \
0                                                  1
1                                                  1
2                                                  1
3                                                  1
4                                                  1

   Fibrosis status (No=0, Yes=1) (Fibrosis 1 and above, there is Fibrosis)  \
0                                                  1
1                                                  0
2                                                  1
3                                                  1
4                                                  0

   Significant Fibrosis (No=0, Yes=1) (If Fibrosis 2 and above, there is Significant Fibrosis)  \
0                                                  0
1                                                  0
2                                                  1
3                                                  0
4                                                  0

   Advanced Fibrosis (No=0, Yes=1) (If Fibrosis is 3 and above, there is Advanced Fibrosis)  \
0                                                  0
1                                                  0
2                                                  1
3                                                  0
4                                                  0

   Cirrhosis (No=0, Yes=1) (If Fibrosis is 4, there is Cirrhosis)  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

   Diagnosis according to SAF (NASH=1, NAFL=2)  \
0                                            1
1                                            1
2                                            1
3                                            1
4                                            1

   Type of Disease (Mild illness=1, Severe illness=2)
0                                                  2
1                                                  2
2                                                  2
3                                                  2
4                                                  2

[5 rows x 50 columns]

In [15]:
# Revisar información general
print(Liver3.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 50 columns):
 #   Column                                                                                       Non-Null Count  Dtype
---  ------                                                                                       --------------  -----
 0   Patient No.                                                                                  605 non-null    int64
 1   Age                                                                                          605 non-null    int64
 2   Gender (Female=1, Male=2)                                                                    605 non-null    int64
 3   Height                                                                                       605 non-null    int64
 4   Weight                                                                                       605 non-null    int64
 5   Body Mass Index                                                                              605 non-null    float64
 6   Waist Circumference                                                                          605 non-null    float64
 7   Hip Circumference                                                                            605 non-null    float64
 8   Systolic Blood Pressure                                                                      605 non-null    int64
 9   Diastolic Blood Pressure                                                                     605 non-null    int64
 10  Diyabetes Mellitus (No=0, Yes=1)                                                             605 non-null    int64
 11  Hypertension (No=0, Yes=1)                                                                   605 non-null    int64
 12  Hyperlipidemia (No=0, Yes=1)                                                                 605 non-null    int64
 13  Metabolic syndrome (No=0, Yes=1)                                                             605 non-null    int64
 14  Smoking Status (Never Smoked=1, Left Smoking=2, Smoking=3)                                   605 non-null    float64
 15  AST                                                                                          605 non-null    float64
 16  ALT                                                                                          605 non-null    int64
 17  ALP                                                                                          605 non-null    float64
 18  GGT                                                                                          605 non-null    float64
 19  LDH                                                                                          605 non-null    float64
 20  Total Bilirubin                                                                              605 non-null    float64
 21  Direct Bilirubin                                                                             605 non-null    float64
 22  Total Protein                                                                                605 non-null    float64
 23  Albumin                                                                                      605 non-null    float64
 24  Total Cholesterol                                                                            605 non-null    int64
 25  Triglycerides                                                                                605 non-null    float64
 26  HDL                                                                                          605 non-null    float64
 27  LDL                                                                                          605 non-null    float64
 28  Leukocyte                                                                                    605 non-null    float64
 29  Hemoglobin                                                                                   605 non-null    float64
 30  Trombosit                                                                                    605 non-null    float64
 31  Mean Corpuscular Volume                                                                      605 non-null    float64
 32  Mean Platelet Volume                                                                         605 non-null    float64
 33  INR                                                                                          605 non-null    float64
 34  Ferritin                                                                                     605 non-null    float64
 35  Glucose                                                                                      605 non-null    float64
 36  BUN                                                                                          605 non-null    float64
 37  Creatinine                                                                                   605 non-null    float64
 38  Hemoglobin - A1C                                                                             605 non-null    float64
 39  Steatosis                                                                                    605 non-null    int64
 40  Activity                                                                                     605 non-null    int64
 41  Fibrosis                                                                                     605 non-null    int64
 42  NAS score according to Kleiner                                                               605 non-null    int64
 43  NAS score>=4 and Fibrosis>=2 (If NAS score>=4 and Fibrosis>=2 = 1, If not = 0)               605 non-null    int64
 44  Fibrosis status (No=0, Yes=1) (Fibrosis 1 and above, there is Fibrosis)                      605 non-null    int64
 45  Significant Fibrosis (No=0, Yes=1) (If Fibrosis 2 and above, there is Significant Fibrosis)  605 non-null    int64
 46  Advanced Fibrosis (No=0, Yes=1) (If Fibrosis is 3 and above, there is Advanced Fibrosis)     605 non-null    int64
 47  Cirrhosis (No=0, Yes=1) (If Fibrosis is 4, there is Cirrhosis)                               605 non-null    int64
 48  Diagnosis according to SAF (NASH=1, NAFL=2)                                                  605 non-null    int64
 49  Type of Disease (Mild illness=1, Severe illness=2)                                           605 non-null    int64
dtypes: float64(26), int64(24)
memory usage: 236.5 KB
None

In [17]:
Liver3.shape

(605, 50)

Veamos los datos faltantes

In [18]:
Liver3.isnull().sum()

Patient No.                                                                                    0
Age                                                                                            0
Gender (Female=1, Male=2)                                                                      0
Height                                                                                         0
Weight                                                                                         0
Body Mass Index                                                                                0
Waist Circumference                                                                            0
Hip Circumference                                                                              0
Systolic Blood Pressure                                                                        0
Diastolic Blood Pressure                                                                       0
Diyabetes Mellitus (No=0, Yes=1)                                                               0
Hypertension (No=0, Yes=1)                                                                     0
Hyperlipidemia (No=0, Yes=1)                                                                   0
Metabolic syndrome (No=0, Yes=1)                                                               0
Smoking Status (Never Smoked=1, Left Smoking=2, Smoking=3)                                     0
AST                                                                                            0
ALT                                                                                            0
ALP                                                                                            0
GGT                                                                                            0
LDH                                                                                            0
Total Bilirubin                                                                                0
Direct Bilirubin                                                                               0
Total Protein                                                                                  0
Albumin                                                                                        0
Total Cholesterol                                                                              0
Triglycerides                                                                                  0
HDL                                                                                            0
LDL                                                                                            0
Leukocyte                                                                                      0
Hemoglobin                                                                                     0
Trombosit                                                                                      0
Mean Corpuscular Volume                                                                        0
Mean Platelet Volume                                                                           0
INR                                                                                            0
Ferritin                                                                                       0
Glucose                                                                                        0
BUN                                                                                            0
Creatinine                                                                                     0
Hemoglobin - A1C                                                                               0
Steatosis                                                                                      0
Activity                                                                                       0
Fibrosis                                                                                       0
NAS score according to Kleiner                                                                 0
NAS score>=4 and Fibrosis>=2 (If NAS score>=4 and Fibrosis>=2 = 1, If not = 0)                 0
Fibrosis status (No=0, Yes=1) (Fibrosis 1 and above, there is Fibrosis)                        0
Significant Fibrosis (No=0, Yes=1) (If Fibrosis 2 and above, there is Significant Fibrosis)    0
Advanced Fibrosis (No=0, Yes=1) (If Fibrosis is 3 and above, there is Advanced Fibrosis)       0
Cirrhosis (No=0, Yes=1) (If Fibrosis is 4, there is Cirrhosis)                                 0
Diagnosis according to SAF (NASH=1, NAFL=2)                                                    0
Type of Disease (Mild illness=1, Severe illness=2)                                             0
dtype: int64

In [20]:
Liver3.isnull().sum().sum()

np.int64(0)

In [21]:
Liver3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 50 columns):
 #   Column                                                                                       Non-Null Count  Dtype
---  ------                                                                                       --------------  -----
 0   Patient No.                                                                                  605 non-null    int64
 1   Age                                                                                          605 non-null    int64
 2   Gender (Female=1, Male=2)                                                                    605 non-null    int64
 3   Height                                                                                       605 non-null    int64
 4   Weight                                                                                       605 non-null    int64
 5   Body Mass Index                                                                              605 non-null    float64
 6   Waist Circumference                                                                          605 non-null    float64
 7   Hip Circumference                                                                            605 non-null    float64
 8   Systolic Blood Pressure                                                                      605 non-null    int64
 9   Diastolic Blood Pressure                                                                     605 non-null    int64
 10  Diyabetes Mellitus (No=0, Yes=1)                                                             605 non-null    int64
 11  Hypertension (No=0, Yes=1)                                                                   605 non-null    int64
 12  Hyperlipidemia (No=0, Yes=1)                                                                 605 non-null    int64
 13  Metabolic syndrome (No=0, Yes=1)                                                             605 non-null    int64
 14  Smoking Status (Never Smoked=1, Left Smoking=2, Smoking=3)                                   605 non-null    float64
 15  AST                                                                                          605 non-null    float64
 16  ALT                                                                                          605 non-null    int64
 17  ALP                                                                                          605 non-null    float64
 18  GGT                                                                                          605 non-null    float64
 19  LDH                                                                                          605 non-null    float64
 20  Total Bilirubin                                                                              605 non-null    float64
 21  Direct Bilirubin                                                                             605 non-null    float64
 22  Total Protein                                                                                605 non-null    float64
 23  Albumin                                                                                      605 non-null    float64
 24  Total Cholesterol                                                                            605 non-null    int64
 25  Triglycerides                                                                                605 non-null    float64
 26  HDL                                                                                          605 non-null    float64
 27  LDL                                                                                          605 non-null    float64
 28  Leukocyte                                                                                    605 non-null    float64
 29  Hemoglobin                                                                                   605 non-null    float64
 30  Trombosit                                                                                    605 non-null    float64
 31  Mean Corpuscular Volume                                                                      605 non-null    float64
 32  Mean Platelet Volume                                                                         605 non-null    float64
 33  INR                                                                                          605 non-null    float64
 34  Ferritin                                                                                     605 non-null    float64
 35  Glucose                                                                                      605 non-null    float64
 36  BUN                                                                                          605 non-null    float64
 37  Creatinine                                                                                   605 non-null    float64
 38  Hemoglobin - A1C                                                                             605 non-null    float64
 39  Steatosis                                                                                    605 non-null    int64
 40  Activity                                                                                     605 non-null    int64
 41  Fibrosis                                                                                     605 non-null    int64
 42  NAS score according to Kleiner                                                               605 non-null    int64
 43  NAS score>=4 and Fibrosis>=2 (If NAS score>=4 and Fibrosis>=2 = 1, If not = 0)               605 non-null    int64
 44  Fibrosis status (No=0, Yes=1) (Fibrosis 1 and above, there is Fibrosis)                      605 non-null    int64
 45  Significant Fibrosis (No=0, Yes=1) (If Fibrosis 2 and above, there is Significant Fibrosis)  605 non-null    int64
 46  Advanced Fibrosis (No=0, Yes=1) (If Fibrosis is 3 and above, there is Advanced Fibrosis)     605 non-null    int64
 47  Cirrhosis (No=0, Yes=1) (If Fibrosis is 4, there is Cirrhosis)                               605 non-null    int64
 48  Diagnosis according to SAF (NASH=1, NAFL=2)                                                  605 non-null    int64
 49  Type of Disease (Mild illness=1, Severe illness=2)                                           605 non-null    int64
dtypes: float64(26), int64(24)
memory usage: 236.5 KB

### Descripción Detallada de las Columnas del DataFrame `Liver3`

In [23]:
import pandas as pd

column_info = []
for col_name, dtype in Liver3.dtypes.items():
    description = ""
    if "Patient No." in col_name: description = "Número de identificación del paciente."
    elif "Age" in col_name: description = "Edad del paciente."
    elif "Gender" in col_name: description = "Género del paciente (1=Femenino, 2=Masculino)."
    elif "Height" in col_name: description = "Altura del paciente."
    elif "Weight" in col_name: description = "Peso del paciente."
    elif "Body Mass Index" in col_name: description = "Índice de Masa Corporal del paciente."
    elif "Waist Circumference" in col_name: description = "Circunferencia de la cintura del paciente."
    elif "Hip Circumference" in col_name: description = "Circunferencia de la cadera del paciente."
    elif "Systolic Blood Pressure" in col_name: description = "Presión arterial sistólica."
    elif "Diastolic Blood Pressure" in col_name: description = "Presión arterial diastólica."
    elif "Diyabetes Mellitus" in col_name: description = "Indicador de Diabetes Mellitus (0=No, 1=Sí)."
    elif "Hypertension" in col_name: description = "Indicador de Hipertensión (0=No, 1=Sí)."
    elif "Hyperlipidemia" in col_name: description = "Indicador de Hiperlipidemia (0=No, 1=Sí)."
    elif "Metabolic syndrome" in col_name: description = "Indicador de Síndrome Metabólico (0=No, 1=Sí)."
    elif "Smoking Status" in col_name: description = "Estado de fumador (1=Nunca fumó, 2=Dejó de fumar, 3=Fumador)."
    elif "AST" in col_name: description = "Nivel de Aspartato Aminotransferasa (enzima hepática)."
    elif "ALT" in col_name: description = "Nivel de Alanina Aminotransferasa (enzima hepática)."
    elif "ALP" in col_name: description = "Nivel de Fosfatasa Alcalina."
    elif "GGT" in col_name: description = "Nivel de Gamma-Glutamil Transferasa."
    elif "LDH" in col_name: description = "Nivel de Lactato Deshidrogenasa."
    elif "Total Bilirubin" in col_name: description = "Nivel total de Bilirrubina."
    elif "Direct Bilirubin" in col_name: description = "Nivel de Bilirrubina Directa."
    elif "Indirect Bilirubin" in col_name: description = "Nivel de Bilirrubina Indirecta."
    elif "Albumin" in col_name: description = "Nivel de Albúmina."
    elif "Globulin" in col_name: description = "Nivel de Globulina."
    elif "Total Protein" in col_name: description = "Nivel de Proteína Total."
    elif "Cholesterol" in col_name: description = "Nivel de Colesterol."
    elif "Triglycerides" in col_name: description = "Nivel de Triglicéridos."
    elif "HDL" in col_name: description = "Nivel de Colesterol HDL (colesterol bueno)."
    elif "LDL" in col_name: description = "Nivel de Colesterol LDL (colesterol malo)."
    elif "VLDL" in col_name: description = "Nivel de Colesterol VLDL."
    elif "Urea" in col_name: description = "Nivel de Urea."
    elif "Creatinine" in col_name: description = "Nivel de Creatinina."
    elif "Glucose" in col_name: description = "Nivel de Glucosa."
    elif "Hemoglobin - A1C" in col_name: description = "Nivel de Hemoglobina Glicosilada (HbA1c)."
    elif "Ferritin" in col_name: description = "Nivel de Ferritina."
    elif "INR" in col_name: description = "Relación Normalizada Internacional (coagulación sanguínea)."
    elif "Mean Platelet Volume" in col_name: description = "Volumen Plaquetario Medio."
    elif "Mean Corpuscular Volume" in col_name: description = "Volumen Corpuscular Medio."
    elif "Trombosit" in col_name: description = "Conteo de Trombocitos (plaquetas)."
    elif "White Blood Cells" in col_name: description = "Conteo de Glóbulos Blancos."
    elif "Red Blood Cells" in col_name: description = "Conteo de Glóbulos Rojos."
    elif "Hemoglobin" in col_name: description = "Nivel de Hemoglobina."
    elif "Hematocrit" in col_name: description = "Nivel de Hematocrito."
    elif "Steatosis" in col_name: description = "Grado de esteatosis (acumulación de grasa en el hígado)."
    elif "Activity" in col_name: description = "Grado de actividad necroinflamatoria."
    elif "Fibrosis" in col_name: description = "Grado de fibrosis hepática."
    elif "NAS score according to Kleiner" in col_name: description = "Puntuación NAS (NAFLD Activity Score) según Kleiner."
    elif "NAS score>=4 and Fibrosis>=2 (If NAS score>=4 and Fibrosis>=2 = 1, If not = 0)" in col_name: description = "Indicador de NAS score >=4 y Fibrosis >=2 (1=Sí, 0=No)."
    elif "Fibrosis status (No=0, Yes=1) (Fibrosis 1 and above, there is Fibrosis)" in col_name: description = "Estado de Fibrosis (0=No, 1=Sí si Fibrosis >= 1)."
    elif "Significant Fibrosis (No=0, Yes=1) (If Fibrosis 2 and above, there is Significant Fibrosis)" in col_name: description = "Indicador de Fibrosis Significativa (0=No, 1=Sí si Fibrosis >= 2)."
    elif "Advanced Fibrosis (No=0, Yes=1) (If Fibrosis is 3 and above, there is Advanced Fibrosis)" in col_name: description = "Indicador de Fibrosis Avanzada (0=No, 1=Sí si Fibrosis >= 3)."
    elif "Cirrhosis (No=0, Yes=1) (If Fibrosis is 4, there is Cirrhosis)" in col_name: description = "Indicador de Cirrosis (0=No, 1=Sí si Fibrosis = 4)."
    elif "Diagnosis according to SAF (NASH=1, NAFL=2)" in col_name: description = "Diagnóstico según SAF (1=NASH, 2=NAFL)."
    elif "Type of Disease (Mild illness=1, Severe illness=2)" in col_name: description = "Tipo de Enfermedad (1=Leve, 2=Grave)."
    elif "Total Cholesterol" in col_name: description = "Nivel de Colesterol Total."
    elif "Leukocyte" in col_name: description = "Conteo de Glóbulos Blancos."
    elif "BUN" in col_name: description = "Nivel de Nitrógeno Ureico en Sangre (BUN)."
    else: description = "Descripción no disponible o inferida."

    column_info.append([col_name, str(dtype), description])

# Create a pandas DataFrame for better display
desc_df = pd.DataFrame(column_info, columns=['Nombre de la Columna', 'Tipo de Dato', 'Descripción Inferida'])
display(desc_df)

,Nombre de la Columna,Tipo de Dato,Descripción Inferida
0,Patient No.,int64,Número de identificación del paciente.
1,Age,int64,Edad del paciente.
2,"Gender (Female=1, Male=2)",int64,"Género del paciente (1=Femenino, 2=Masculino)."
3,Height,int64,Altura del paciente.
4,Weight,int64,Peso del paciente.
5,Body Mass Index,float64,Índice de Masa Corporal del paciente.
6,Waist Circumference,float64,Circunferencia de la cintura del paciente.
7,Hip Circumference,float64,Circunferencia de la cadera del paciente.
8,Systolic Blood Pressure,int64,Presión arterial sistólica.
9,Diastolic Blood Pressure,int64,Presión arterial diastólica.
10,"Diyabetes Mellitus (No=0, Yes=1)",int64,"Indicador de Diabetes Mellitus (0=No, 1=Sí)."
11,"Hypertension (No=0, Yes=1)",int64,"Indicador de Hipertensión (0=No, 1=Sí)."
12,"Hyperlipidemia (No=0, Yes=1)",int64,"Indicador de Hiperlipidemia (0=No, 1=Sí)."
13,"Metabolic syndrome (No=0, Yes=1)",int64,"Indicador de Síndrome Metabólico (0=No, 1=Sí)."
14,"Smoking Status (Never Smoked=1, Left Smoking=2...",float64,"Estado de fumador (1=Nunca fumó, 2=Dejó de fum..."
15,AST,float64,Nivel de Aspartato Aminotransferasa (enzima he...
16,ALT,int64,Nivel de Alanina Aminotransferasa (enzima hepá...
17,ALP,float64,Nivel de Fosfatasa Alcalina.
18,GGT,float64,Nivel de Gamma-Glutamil Transferasa.
19,LDH,float64,Nivel de Lactato Deshidrogenasa.
20,Total Bilirubin,float64,Nivel total de Bilirrubina.
21,Direct Bilirubin,float64,Nivel de Bilirrubina Directa.
22,Total Protein,float64,Nivel de Proteína Total.
23,Albumin,float64,Nivel de Albúmina.
24,Total Cholesterol,int64,Nivel de Colesterol.
25,Triglycerides,float64,Nivel de Triglicéridos.
26,HDL,float64,Nivel de Colesterol HDL (colesterol bueno).
27,LDL,float64,Nivel de Colesterol LDL (colesterol malo).
28,Leukocyte,float64,Conteo de Glóbulos Blancos.
29,Hemoglobin,float64,Nivel de Hemoglobina.
30,Trombosit,float64,Conteo de Trombocitos (plaquetas).
31,Mean Corpuscular Volume,float64,Volumen Corpuscular Medio.
32,Mean Platelet Volume,float64,Volumen Plaquetario Medio.
33,INR,float64,Relación Normalizada Internacional (coagulació...
34,Ferritin,float64,Nivel de Ferritina.
35,Glucose,float64,Nivel de Glucosa.
36,BUN,float64,Nivel de Nitrógeno Ureico en Sangre (BUN).
37,Creatinine,float64,Nivel de Creatinina.
38,Hemoglobin - A1C,float64,Nivel de Hemoglobina Glicosilada (HbA1c).
39,Steatosis,int64,Grado de esteatosis (acumulación de grasa en e...
40,Activity,int64,Grado de actividad necroinflamatoria.
41,Fibrosis,int64,Grado de fibrosis hepática.
42,NAS score according to Kleiner,int64,Puntuación NAS (NAFLD Activity Score) según Kl...
43,NAS score>=4 and Fibrosis>=2 (If NAS score>=4 ...,int64,Grado de fibrosis hepática.
44,"Fibrosis status (No=0, Yes=1) (Fibrosis 1 and ...",int64,Grado de fibrosis hepática.
45,"Significant Fibrosis (No=0, Yes=1) (If Fibrosi...",int64,Grado de fibrosis hepática.
46,"Advanced Fibrosis (No=0, Yes=1) (If Fibrosis i...",int64,Grado de fibrosis hepática.
47,"Cirrhosis (No=0, Yes=1) (If Fibrosis is 4, the...",int64,Grado de fibrosis hepática.
48,"Diagnosis according to SAF (NASH=1, NAFL=2)",int64,"Diagnóstico según SAF (1=NASH, 2=NAFL)."
49,"Type of Disease (Mild illness=1, Severe illnes...",int64,"Tipo de Enfermedad (1=Leve, 2=Grave)."

In [24]:
output_csv_path_liver3 = "Liver3_final.csv"
Liver3.to_csv(output_csv_path_liver3, index=False)
print(f"El DataFrame 'Liver3' ha sido guardado como '{output_csv_path_liver3}' en el directorio actual de Colab.")

El DataFrame 'Liver3' ha sido guardado como 'Liver3_final.csv' en el directorio actual de Colab.

### Descripción de las Columnas del DataFrame `Liver3`